import colors,challenge
'''
Uncomment each challenge and corresponding challenge test as you go along, 
    you will be programming in each challenge_x function, and will be expected to return a value. 
    
    By running this program, you will get instant, hopefully verbose enough feedback.
'''

#You are given this one for free
def challenge_1():
    return "Hello, World!"


#What is 3*5?



def challenge_2():
    return 5*3

#If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
#Find the sum of all multiples of 3 or 5 below 1000

#def challenge_3():

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''
#def challenge_4():

'''
The prime factors of 13195 are 5, 7, 13 and 29.
What is the largest prime factor of the number 600851475143 ?
'''
#def challenge_5(inp):

'''
CHALLENGE TESTS, DO NOT EDIT ANYTHING BELOW THIS COMMENT
CHALLENGE TESTS, DO NOT EDIT ANYTHING BELOW THIS COMMENT
CHALLENGE TESTS, DO NOT EDIT ANYTHING BELOW THIS COMMENT
CHALLENGE TESTS, DO NOT EDIT ANYTHING BELOW THIS COMMENT
CHALLENGE TESTS, DO NOT EDIT ANYTHING BELOW THIS COMMENT
CHALLENGE TESTS, DO NOT EDIT ANYTHING BELOW THIS COMMENT
CHALLENGE TESTS, DO NOT EDIT ANYTHING BELOW THIS COMMENT
CHALLENGE TESTS, DO NOT EDIT ANYTHING BELOW THIS COMMENT
CHALLENGE TESTS, DO NOT EDIT ANYTHING BELOW THIS COMMENT
CHALLENGE TESTS, DO NOT EDIT ANYTHING BELOW THIS COMMENT
CHALLENGE TESTS, DO NOT EDIT ANYTHING BELOW THIS COMMENT
'''
def _():
    print(colors.fg.orange+colors.uglyline+colors.reset)

_()
#You are given this one for free
print(colors.fg.yellow+"CHALLENGE TEST 1:"+challenge.challenge_test(challenge_1(),"Hello, World!"))
_()
print(colors.fg.yellow+"CHALLENGE TEST 2:"+challenge.challenge_test(challenge_2(),(3*5)))
_()
#print(colors.fg.yellow+"CHALLENGE TEST 3:"+challenge.challenge_test(challenge_3(),challenge.challenge3))
_()
#print(colors.fg.yellow+"CHALLENGE TEST 4:"+challenge.challenge_test(challenge_4(),challenge.challenge4))
_()
#print(colors.fg.yellow+"CHALLENGE TEST 5:"+challenge.challenge_test(challenge_5(600851475143),challenge.challenge5))
_()
